version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DOMAIN: localhost
      ENVIRONMENT: local
      PROJECT_NAME: "Full Stack FastAPI Project"
      STACK_NAME: full-stack-fastapi-project
      BACKEND_CORS_ORIGINS: http://localhost,http://localhost:5173,https://localhost,https://localhost:5173
      SECRET_KEY: Genvic12
      FIRST_SUPERUSER: devops@hng.tech
      FIRST_SUPERUSER_PASSWORD: devops#HNG11
      USERS_OPEN_REGISTRATION: True
      SMTP_HOST: smtp.gmail.com
      SMTP_USER: devops@gmail.com
      SMTP_PASSWORD: Genvic12
      EMAILS_FROM_EMAIL: info@example.com
      SMTP_TLS: True
      SMTP_SSL: False
      SMTP_PORT: 587
      POSTGRES_SERVER: postgresdb
      POSTGRES_PORT: 5432
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: Genvic12
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`, `/docs`, `/redoc`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: Genvic12

  adminer:
    image: adminer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`db.localhost`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

  traefik:
    image: traefik:v2.3
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
